const users = {
  user1: {
    info: {
      fullName: name,
      age: age,
      gender: gender,
      bodyWeight: weight,
      regData: newPaddedDate,
    },
    userBody: {
      chest: [],
      armLeft: [],
      armRight: [],
      forearmLeft: [],
      forearmRight: [],
      quadLeft: [],
      quadRight: [],
      calfLeft: [],
      calfRight: [],
      bodyWeight: [],
      neck: [],
      waistline: [],
    },
    training: {
      chest: [],
      armLeft: [],
      armRight: [],
      forearmLeft: [],
      forearmRight: [],
      quadLeft: [],
      quadRight: [],
      calfLeft: [],
      calfRight: [],
      neck: [],
      waistline: [],
    },
    medicalInfo: {},
  },
  user2: {
    info: {
      fullName: name,
      age: age,
      gender: gender,
      bodyWeight: weight,
      regData: newPaddedDate,
    },
    userBody: {
      chest: [],
      armLeft: [],
      armRight: [],
      forearmLeft: [],
      forearmRight: [],
      quadLeft: [],
      quadRight: [],
      calfLeft: [],
      calfRight: [],
      bodyWeight: [],
      neck: [],
      waistline: [],
    },
    training: {
      chest: [],
      armLeft: [],
      armRight: [],
      forearmLeft: [],
      forearmRight: [],
      quadLeft: [],
      quadRight: [],
      calfLeft: [],
      calfRight: [],
      neck: [],
      waistline: [],
    },
    medicalInfo: {},
  },
};
